In [2]:
sc

In [6]:
import csv
# data =  sc.textFile('coalesce_joined_weather_collisions_sorted_fixed.csv')
df = spark.read.load('joins_in_2015.csv', format='csv', header=True, inferSchema=False)
df.cache()


df.registerTempTable('df')



from pyspark.sql.types import IntegerType

inj_kil = [ "NUMBER_OF_CYCLIST_INJURED",
            "NUMBER_OF_CYCLIST_KILLED",
            "NUMBER_OF_MOTORIST_INJURED",
            "NUMBER_OF_MOTORIST_KILLED",
            "NUMBER_OF_PEDESTRIANS_INJURED",
            "NUMBER_OF_PEDESTRIANS_KILLED",
            "NUMBER_OF_PERSONS_INJURED",
            "NUMBER_OF_PERSONS_KILLED"
            ]

for x in inj_kil:
    df = df.withColumn(x, df[x].cast(IntegerType()))

if __name__=='__main__':
    sc = SparkContext()
    spark = SparkSession(sc)
    sqlContext = SQLContext(sc)    
    df = spark.read.load('hdfs:///user/dzeng01/project/joined_weather_collisions_sorted_fixed.csv', format='csv', header=True, inferSchema=False)
    temp = spark.sql(query)

In [8]:
df.take(1)

[Row(BOROUGH=u'QUEENS', CONTRIBUTING_FACTOR_VEHICLE_1=u'Traffic Control Disregarded', CONTRIBUTING_FACTOR_VEHICLE_2=None, CONTRIBUTING_FACTOR_VEHICLE_3=None, CONTRIBUTING_FACTOR_VEHICLE_4=None, CONTRIBUTING_FACTOR_VEHICLE_5=None, CROSS_STREET_NAME=u'193 STREET', DATETIME=u'2015-01-01 00:20:00', LATITUDE=u'40.7518471', LOCATION=u'(40.7518471, -73.787862)', LONGITUDE=u'-73.787862', NUMBER_OF_CYCLIST_INJURED=0, NUMBER_OF_CYCLIST_KILLED=0, NUMBER_OF_MOTORIST_INJURED=0, NUMBER_OF_MOTORIST_KILLED=0, NUMBER_OF_PEDESTRIANS_INJURED=0, NUMBER_OF_PEDESTRIANS_KILLED=0, NUMBER_OF_PERSONS_INJURED=0, NUMBER_OF_PERSONS_KILLED=0, OFF_STREET_NAME=None, ON_STREET_NAME=u'47 AVENUE', UNIQUE_KEY=u'3146911', VEHICLE_TYPE_CODE_1=u'SPORT UTILITY / STATION WAGON', VEHICLE_TYPE_CODE_2=None, VEHICLE_TYPE_CODE_3=None, VEHICLE_TYPE_CODE_4=None, VEHICLE_TYPE_CODE_5=None, ZIP_CODE=u'11358', _c28=u'43066', Conditions=u'Clear', DateUTC=u'2015-01-01 05:51:00', DatetimeEDT=u'2015-01-01 00:51:00', Dew_PointF=u'8.1', Events=None, Freezing=u'1', Gust_SpeedMPH=u'17.3', Humidity=u'43', LowVisibility=u'0', PrecipitationIn=u'N/A', Rain=u'0', Sea_Level_PressureIn=u'30.14', Snow=u'0', TemperatureF=u'28.0', TimeEDT=u'12:51 AM', VisibilityMPH=u'10.0', WindDirDegrees=u'250', Wind_Direction=u'WSW', Wind_SpeedMPH=u'10.4', Windy=u'0')]

In [10]:
# df.dtypes

In [12]:
from pyspark.sql.functions import udf
from pyspark.sql.types import FloatType
def filter_general(x):
    if x > 65:
        return float(x)
    else:
        return float(0)
    
gfg = udf(filter_general, FloatType())
newcol = df.withColumn("Dew_PointF", gfg("Dew_PointF"))
newcol.take(5)

In [32]:
# sqlContext.sql('select * from df where Rain=1')
from pyspark.sql.functions import col
from calendar import monthrange
import json


#date = ""

# Yearly statistics


def months(x):
    month = {1:"January",
             2:"Feburary",
             3:"March",
             4:"April",
             5:"May",
             6:"June",
             7:"July",
             8:"August",
             9:"September",
             10:"October",
             11:"November",
             12:"December"}
    return str(month[x])



for yr in range(15,16):
    
    #### This should be code that will read in each csv for each year and register as df.
    stats = {}
    stats["0_YEAR"] = int(str(20)+str(yr))   
    
    
    ## Overall Statistics
    stats['Overall'] = {}
    m_arr = []
    mi_arr = []
    md_arr = []
    
    """PREPROCESSING"""
    for x in range(1,13):
        date = "20{1}-0{0}%".format(x, yr) if x < 10 else "20{1}-{0}%".format(x, yr)
        query = 'select * from df where DATETIME like "{0}"'.format(date)
        m_arr.append((x, sqlContext.sql(query).count())) 
    total = sum([x[1] for x in m_arr])
        
    for x in range(1,13):
        date = "20{1}-0{0}%".format(x, yr) if x < 10 else "20{1}-{0}%".format(x, yr)
        query = 'select * from df where DATETIME like "{0}" and ( \
                                                                NUMBER_OF_CYCLIST_INJURED!=0 or \
                                                                NUMBER_OF_MOTORIST_INJURED!=0 or \
                                                                NUMBER_OF_PEDESTRIANS_INJURED!=0 or \
                                                                NUMBER_OF_PERSONS_INJURED!=0)'.format(date)
        mi_arr.append((x, sqlContext.sql(query).count()))   
    injury_total = sum([x[1] for x in mi_arr])
    
    
    for x in range(1,13):
        date = "20{1}-0{0}%".format(x, yr) if x < 10 else "20{1}-{0}%".format(x, yr)
        query = 'select * from df where DATETIME like "{0}" and ( \
                                                                NUMBER_OF_CYCLIST_KILLED!=0 or \
                                                                NUMBER_OF_MOTORIST_KILLED!=0 or \
                                                                NUMBER_OF_PEDESTRIANS_KILLED!=0 or \
                                                                NUMBER_OF_PERSONS_KILLED!=0)'.format(date)
        md_arr.append((x, sqlContext.sql(query).count()))   
    death_total = sum([x[1] for x in md_arr])
    
    # Statistics
    stats['Overall']['Total Number of Collisions in Year'] = total
    stats['Overall']['Total Number of Collisions w/ Injury in Year'] = injury_total
    stats['Overall']['Total Number of Collisions w/ Death in Year'] = death_total
    stats['Overall']['Average Collisions Per Month'] = total // 12
    stats['Overall']['Average Collisions Per Day'] = total // 365
    stats['Overall']['Monthly Adjusted Average Weight (%)'] = [str(
                                            (months(x+1), round((float(m_arr[x][1])/float(total)*100.0),2))
                                                                ) for x in range(0,12)]
    stats['Overall']['Collisions Per Month'] = [str(
                                                (months(x+1), m_arr[x][1])
                                                ) for x in range(0,12)]
    stats['Overall']['Average Collisions Per Day (Monthly)'] = [str(
                                         (months(x+1), m_arr[x][1]/monthrange(int(str(20)+str(yr)), x+1)[1])
                                                                ) for x in range(0,12)]
    stats['Overall']['Injury Rate (Year %)'] = float(injury_total)/float(total) * 100.00
    stats['Overall']['Death Rate (Year %)'] = float(death_total)/float(total) * 100.00
    stats['Overall']['Number of Collisions w/ Injuries Per Month'] = [str(
                                                                    (months(x+1), mi_arr[x][1])
                                                                    ) for x in range(0,12)]
    stats['Overall']['Number of Collisions w/ Deaths Per Month'] = [str(
                                                                    (months(x+1), md_arr[x][1])
                                                                    ) for x in range(0,12)]
    stats['Overall']['Injury Rate Per Month (Month %)'] = [str(
                                                        (months(x+1), round((float(mi_arr[x][1])/float(m_arr[x][1]) * 100.00),2))
                                                        ) for x in range(0,12) if m_arr[x][1] != 0]
    stats['Overall']['Death Rate Per Month (Month %)'] = [str(
                                                        (months(x+1), round((float(md_arr[x][1])/float(m_arr[x][1]) * 100.00),2))
                                                        ) for x in range(0,12) if m_arr[x][1] != 0]
    
    # Rain Statistics
    stats['Rain'] = {}
    r_arr = []
    ri_arr = []
    rd_arr = []

    """PREPROCESSING"""
    for x in range(1,13):
        date = "20{1}-0{0}%".format(x, yr) if x < 10 else "20{1}-{0}%".format(x, yr)
        query = 'select * from df where Rain="1" and DATETIME like "{0}"'.format(date)
        r_arr.append((x, sqlContext.sql(query).count()))
    rain_total = sum([x[1] for x in r_arr])
    
    
    for x in range(1,13):
        date = "20{1}-0{0}%".format(x, yr) if x < 10 else "20{1}-{0}%".format(x, yr)
        query = 'select * from df where Rain="1" and DATETIME like "{0}" and ( \
                                                                NUMBER_OF_CYCLIST_INJURED!=0 or \
                                                                NUMBER_OF_MOTORIST_INJURED!=0 or \
                                                                NUMBER_OF_PEDESTRIANS_INJURED!=0 or \
                                                                NUMBER_OF_PERSONS_INJURED!=0)'.format(date)
        ri_arr.append((x, sqlContext.sql(query).count()))
    rain_injury_total = sum([x[1] for x in ri_arr])
    
    
    for x in range(1,13):
        date = "20{1}-0{0}%".format(x, yr) if x < 10 else "20{1}-{0}%".format(x, yr)
        query = 'select * from df where Rain="1" and DATETIME like "{0}" and ( \
                                                                NUMBER_OF_CYCLIST_KILLED!=0 or \
                                                                NUMBER_OF_MOTORIST_KILLED!=0 or \
                                                                NUMBER_OF_PEDESTRIANS_KILLED!=0 or \
                                                                NUMBER_OF_PERSONS_KILLED!=0)'.format(date)
        rd_arr.append((x, sqlContext.sql(query).count()))
    rain_death_total = sum([x[1] for x in rd_arr])
    
    
    
    # Statistics
    stats['Rain']['Total Number of Collisions w/ Injury & Rain in Year'] = rain_injury_total
    stats['Rain']['Total Number of Collisions w/ Death & Rain in Year'] = rain_death_total
    stats['Rain']['Injury Rate w/ Rain (Year %)'] = float(rain_injury_total)/float(rain_total) * 100.00
    stats['Rain']['Death Rate w/ Rain (Year %)'] = float(rain_death_total)/float(rain_total) * 100.00
    stats['Rain']['Total Number of Rain Collisions in Year'] = rain_total
    stats['Rain']['Percent of Collisions in Rain Over Year (%)'] = (float(rain_total) / float(total)) * 100.00
    stats['Rain']['Collisions in Rain'] = [str(
                                        (months(x+1), r_arr[x][1])
                                        ) for x in range(0,12)]
    stats['Rain']['Average Collisions in Rain Per Month'] = rain_total//12
    stats['Rain']['Number of Collisions w/ Injuries and Rain Per Month'] = [str(
                                                                            (months(x+1), ri_arr[x][1])
                                                                            ) for x in range(0,12)]
    stats['Rain']['Number of Collisions w/ Deaths and Rain Per Month'] = [str(
                                                                            (months(x+1), rd_arr[x][1])
                                                                            ) for x in range(0,12)]
    stats['Rain']['Percent of Collisions in Each Month That Are Rain Collisions (Rain %)'] = [str(
                                                            (months(x+1), round((float(r_arr[x][1])/float(m_arr[x][1]))*100.0, 2))
                                                            ) for x in range(0,12) if m_arr[x][1] != 0]
    stats['Rain']['Injury Rate Per Month w/ Rain (Month %)'] = [str(
                                                            (months(x+1), round((float(ri_arr[x][1])/float(r_arr[x][1]) * 100.00),2))
                                                            ) for x in range(0,12) if r_arr[x][1] != 0]
    stats['Rain']['Death Rate Per Month w/ Rain (Month %)'] = [str(
                                                            (months(x+1), round((float(rd_arr[x][1])/float(r_arr[x][1]) * 100.00),2))
                                                            ) for x in range(0,12) if r_arr[x][1] != 0]
    
    
    
    print json.dumps(stats, indent=4, sort_keys=True)
#     print stats


# print arr

# Monthly Statistics

# for x in [date]:
    
#     a = sqlContext.sql('select * from df where Rain=1')
#     a.coalesce(1).write.csv('rain', header=True)

#     a = sqlContext.sql('select * from df where Snow=1')
#     a.coalesce(1).write.csv('snow', header=True)

#     a = sqlContext.sql('select * from df where Freezing=1')
#     a.coalesce(1).write.csv('freezing', header=True)

#     a = sqlContext.sql('select * from df where LowVisibility=1')
#     a.coalesce(1).write.csv('foggy', header=True)

#     a = sqlContext.sql('select * from df where Windy=1')
#     a.coalesce(1).write.csv('windy', header=True)


# df = df.filter(df.LATITUDE != '0')

# from pyspark.sql.functions import col


# a = df.where(col("LOCATION").isNotNull())
# a.coalesce(1).write.csv('geodata', header=True)

{
    "0_YEAR": 2015,
    "Overall": {
        "Average Collisions Per Day": 595,
        "Average Collisions Per Day (Monthly)": [
            "('January', 520)",
            "('Feburary', 559)",
            "('March', 578)",
            "('April', 559)",
            "('May', 621)",
            "('June', 627)",
            "('July', 604)",
            "('August', 612)",
            "('September', 616)",
            "('October', 639)",
            "('November', 596)",
            "('December', 608)"
        ],
        "Average Collisions Per Month": 18118,
        "Collisions Per Month": [
            "('January', 16122)",
            "('Feburary', 15674)",
            "('March', 17947)",
            "('April', 16789)",
            "('May', 19269)",
            "('June', 18818)",
            "('July', 18740)",
            "('August', 18973)",
            "('September', 18489)",
            "('October', 19830)",
            "('November', 17899)",
            "('December', 18867)"
        ],
        "Death Rate (Year %)": 0.10808722409011255,
        "Death Rate Per Month (Month %)": [
            "('January', 0.1)",
            "('Feburary', 0.1)",
            "('March', 0.06)",
            "('April', 0.11)",
            "('May', 0.15)",
            "('June', 0.11)",
            "('July', 0.1)",
            "('August', 0.12)",
            "('September', 0.08)",
            "('October', 0.12)",
            "('November', 0.14)",
            "('December', 0.12)"
        ],
        "Injury Rate (Year %)": 17.393304111454025,
        "Injury Rate Per Month (Month %)": [
            "('January', 15.88)",
            "('Feburary', 14.19)",
            "('March', 15.08)",
            "('April', 16.8)",
            "('May', 18.51)",
            "('June', 17.88)",
            "('July', 18.32)",
            "('August', 18.41)",
            "('September', 18.34)",
            "('October', 18.17)",
            "('November', 18.04)",
            "('December', 18.14)"
        ],
        "Monthly Adjusted Average Weight (%)": [
            "('January', 7.42)",
            "('Feburary', 7.21)",
            "('March', 8.25)",
            "('April', 7.72)",
            "('May', 8.86)",
            "('June', 8.66)",
            "('July', 8.62)",
            "('August', 8.73)",
            "('September', 8.5)",
            "('October', 9.12)",
            "('November', 8.23)",
            "('December', 8.68)"
        ],
        "Number of Collisions w/ Deaths Per Month": [
            "('January', 16)",
            "('Feburary', 16)",
            "('March', 11)",
            "('April', 19)",
            "('May', 29)",
            "('June', 20)",
            "('July', 18)",
            "('August', 22)",
            "('September', 14)",
            "('October', 23)",
            "('November', 25)",
            "('December', 22)"
        ],
        "Number of Collisions w/ Injuries Per Month": [
            "('January', 2560)",
            "('Feburary', 2224)",
            "('March', 2707)",
            "('April', 2821)",
            "('May', 3567)",
            "('June', 3364)",
            "('July', 3433)",
            "('August', 3493)",
            "('September', 3391)",
            "('October', 3604)",
            "('November', 3229)",
            "('December', 3423)"
        ],
        "Total Number of Collisions in Year": 217417,
        "Total Number of Collisions w/ Death in Year": 235,
        "Total Number of Collisions w/ Injury in Year": 37816
    },
    "Rain": {
        "Average Collisions in Rain Per Month": 956,
        "Collisions in Rain": [
            "('January', 1306)",
            "('Feburary', 235)",
            "('March', 1212)",
            "('April', 693)",
            "('May', 522)",
            "('June', 1553)",
            "('July', 536)",
            "('August', 275)",
            "('September', 617)",
            "('October', 1565)",
            "('November', 1041)",
            "('December', 1924)"
        ],
        "Death Rate Per Month w/ Rain (Month %)": [
            "('January', 0.08)",
            "('Feburary', 0.0)",
            "('March', 0.08)",
            "('April', 0.0)",
            "('May', 0.19)",
            "('June', 0.06)",
            "('July', 0.19)",
            "('August', 0.0)",
            "('September', 0.0)",
            "('October', 0.06)",
            "('November', 0.0)",
            "('December', 0.0)"
        ],
        "Death Rate w/ Rain (Year %)": 0.052269361442634374,
        "Injury Rate Per Month w/ Rain (Month %)": [
            "('January', 18.76)",
            "('Feburary', 13.62)",
            "('March', 20.21)",
            "('April', 17.75)",
            "('May', 21.65)",
            "('June', 17.39)",
            "('July', 20.34)",
            "('August', 18.18)",
            "('September', 19.29)",
            "('October', 18.91)",
            "('November', 20.85)",
            "('December', 22.09)"
        ],
        "Injury Rate w/ Rain (Year %)": 19.548741179545257,
        "Number of Collisions w/ Deaths and Rain Per Month": [
            "('January', 1)",
            "('Feburary', 0)",
            "('March', 1)",
            "('April', 0)",
            "('May', 1)",
            "('June', 1)",
            "('July', 1)",
            "('August', 0)",
            "('September', 0)",
            "('October', 1)",
            "('November', 0)",
            "('December', 0)"
        ],
        "Number of Collisions w/ Injuries and Rain Per Month": [
            "('January', 245)",
            "('Feburary', 32)",
            "('March', 245)",
            "('April', 123)",
            "('May', 113)",
            "('June', 270)",
            "('July', 109)",
            "('August', 50)",
            "('September', 119)",
            "('October', 296)",
            "('November', 217)",
            "('December', 425)"
        ],
        "Percent of Collisions in Each Month That Are Rain Collisions (Rain %)": [
            "('January', 8.1)",
            "('Feburary', 1.5)",
            "('March', 6.75)",
            "('April', 4.13)",
            "('May', 2.71)",
            "('June', 8.25)",
            "('July', 2.86)",
            "('August', 1.45)",
            "('September', 3.34)",
            "('October', 7.89)",
            "('November', 5.82)",
            "('December', 10.2)"
        ],
        "Percent of Collisions in Rain Over Year (%)": 5.279715937576179,
        "Total Number of Collisions w/ Death & Rain in Year": 6,
        "Total Number of Collisions w/ Injury & Rain in Year": 2244,
        "Total Number of Rain Collisions in Year": 11479
    }
}

In [31]:
print(float(217417) / float(35408))

6.1403355174

In [19]:
        query = 'select sum(NUMBER_OF_CYCLIST_INJURED) from df'
        a = sqlContext.sql(query)

In [14]:
df.groupBy("CONTRIBUTING_FACTOR_VEHICLE_1").count().orderBy('count', ascending=False).show()

+-----------------------------+-----+
|CONTRIBUTING_FACTOR_VEHICLE_1|count|
+-----------------------------+-----+
|                  Unspecified|97119|
|         Driver Inattentio...|31975|
|              Fatigued/Drowsy|15466|
|         Failure to Yield ...|10539|
|              Other Vehicular|10513|
|             Backing Unsafely| 7121|
|           Turning Improperly| 6542|
|           Lost Consciousness| 6280|
|         Prescription Medi...| 4625|
|         Traffic Control D...| 3136|
|         Outside Car Distr...| 2841|
|            Pavement Slippery| 2821|
|          Driver Inexperience| 2751|
|          Physical Disability| 2626|
|          Alcohol Involvement| 1826|
|            Oversized Vehicle| 1594|
|         Passenger Distrac...| 1171|
|         View Obstructed/L...|  877|
|                         null|  805|
|         Aggressive Drivin...|  795|
+-----------------------------+-----+
only showing top 20 rows

In [236]:
from pyspark.sql.functions import col
test = df.filter(col('DATETIME').like("2016-11%")).groupBy("NUMBER_OF_CYCLIST_INJURED").count().orderBy('count', ascending=False).rdd.map(lambda x: (x['NUMBER_OF_CYCLIST_INJURED'], x['count'])).collect()

In [237]:
test

[(0, 18847), (1, 361), (2, 25), (3, 2)]

In [233]:
df.filter(col('DATETIME').like("2016-10%"))

DataFrame[BOROUGH: string, CONTRIBUTING_FACTOR_VEHICLE_1: string, CONTRIBUTING_FACTOR_VEHICLE_2: string, CONTRIBUTING_FACTOR_VEHICLE_3: string, CONTRIBUTING_FACTOR_VEHICLE_4: string, CONTRIBUTING_FACTOR_VEHICLE_5: string, CROSS_STREET_NAME: string, DATETIME: string, LATITUDE: string, LOCATION: string, LONGITUDE: string, NUMBER_OF_CYCLIST_INJURED: int, NUMBER_OF_CYCLIST_KILLED: int, NUMBER_OF_MOTORIST_INJURED: int, NUMBER_OF_MOTORIST_KILLED: int, NUMBER_OF_PEDESTRIANS_INJURED: int, NUMBER_OF_PEDESTRIANS_KILLED: int, NUMBER_OF_PERSONS_INJURED: int, NUMBER_OF_PERSONS_KILLED: int, OFF_STREET_NAME: string, ON_STREET_NAME: string, UNIQUE_KEY: string, VEHICLE_TYPE_CODE_1: string, VEHICLE_TYPE_CODE_2: string, VEHICLE_TYPE_CODE_3: string, VEHICLE_TYPE_CODE_4: string, VEHICLE_TYPE_CODE_5: string, ZIP_CODE: string, _c28: string, Conditions: string, DateUTC: string, DatetimeEDT: string, Dew_PointF: string, Events: string, Freezing: string, Gust_SpeedMPH: string, Humidity: string, LowVisibility: string, PrecipitationIn: string, Rain: string, Sea_Level_PressureIn: string, Snow: string, TemperatureF: string, TimeEDT: string, VisibilityMPH: string, WindDirDegrees: string, Wind_Direction: string, Wind_SpeedMPH: string, Windy: string]

In [242]:
df.select("LOCATION").groupBy("LOCATION").count().orderBy('count', ascending=False).show()

+--------------------+-----+
|            LOCATION|count|
+--------------------+-----+
|                null|63518|
|(40.7197624, -73....|   70|
|(40.608757, -74.0...|   60|
|(40.79522, -73.92...|   56|
|(40.6916827, -73....|   47|
|(40.6960346, -73....|   45|
|(40.8047, -73.91243)|   43|
|(40.820189, -73.8...|   37|
|(40.820305, -73.8...|   36|
|(40.7044959, -73....|   36|
|(40.79537, -73.92...|   36|
|(40.8451897, -73....|   36|
|(40.7014547, -73....|   34|
|(40.602806, -74.0...|   34|
|(40.7606, -73.96434)|   33|
|(40.798256, -73.8...|   33|
|(40.7606005, -73....|   33|
|(40.8360929, -73....|   33|
|(40.696033, -73.9...|   32|
|(40.861862, -73.9...|   32|
+--------------------+-----+
only showing top 20 rows

In [15]:
df.select("LOCATION").groupBy("LOCATION").count().orderBy('count', ascending=False).rdd.flatMap(lambda x: x).collect()

[None,
 34672,
 u'(40.8100528, -73.9251435)',
 219,
 u'(40.6528929, -73.8667311)',
 136,
 u'(40.6960346, -73.9845292)',
 135,
 u'(40.7606005, -73.9643142)',
 132,
 u'(40.7460781, -73.9749359)',
 116,
 u'(40.7595273, -73.999242)',
 112,
 u'(40.6757357, -73.8968533)',
 111,
 u'(40.7572323, -73.9897922)',
 108,
 u'(40.7203211, -73.9940403)',
 105,
 u'(40.7602226, -73.967462)',
 103,
 u'(40.6585778, -73.8906229)',
 96,
 u'(40.7584292, -73.9926328)',
 95,
 u'(40.8571285, -73.8807926)',
 92,
 u'(40.6781627, -73.8974769)',
 90,
 u'(40.8618642, -73.9127392)',
 90,
 u'(40.7832478, -73.9447234)',
 90,
 u'(40.8027515, -73.933575)',
 88,
 u'(40.759308, -73.9652931)',
 88,
 u'(40.6631828, -73.9624487)',
 87,
 u'(40.7241363, -73.9926041)',
 87,
 u'(40.7509908, -73.9906233)',
 87,
 u'(40.680015, -73.8774282)',
 85,
 u'(40.820189, -73.8906752)',
 84,
 u'(40.7548409, -73.9841185)',
 83,
 u'(40.7502939, -73.9948425)',
 82,
 u'(40.6596509, -73.7738282)',
 82,
 u'(40.7334973, -73.8703694)',
 80,
 u'(40.7615508, -73.9665842)',
 80,
 u'(40.6774132, -73.9303181)',
 79,
 u'(40.7589782, -73.9939358)',
 78,
 u'(40.7476292, -73.9767362)',
 78,
 u'(40.7666318, -73.8890253)',
 77,
 u'(40.6840525, -73.9774579)',
 77,
 u'(40.6561603, -73.7673526)',
 77,
 u'(40.7643229, -73.977196)',
 77,
 u'(40.762025, -74.0011515)',
 76,
 u'(40.7193963, -74.0018831)',
 75,
 u'(40.6339615, -74.0147538)',
 75,
 u'(40.7631141, -73.9625151)',
 74,
 u'(40.74478, -73.9758819)',
 73,
 u'(40.754584, -73.9991446)',
 72,
 u'(40.7168135, -73.9977634)',
 71,
 u'(40.7591997, -73.9846193)',
 70,
 u'(40.6687978, -73.9311201)',
 69,
 u'(40.7608228, -73.9983142)',
 69,
 u'(40.7514416, -73.9760491)',
 69,
 u'(40.6761899, -73.9080899)',
 69,
 u'(40.7545534, -73.7431647)',
 68,
 u'(40.8137456, -73.9313928)',
 68,
 u'(40.7618573, -73.9634255)',
 68,
 u'(40.7466818, -73.9744953)',
 67,
 u'(40.7520589, -74.0009817)',
 67,
 u'(40.8285193, -73.8411794)',
 67,
 u'(40.7199725, -73.9928968)',
 66,
 u'(40.7642781, -73.9730158)',
 66,
 u'(40.8481201, -73.9308839)',
 66,
 u'(40.7429104, -73.9928041)',
 66,
 u'(40.8043758, -73.9374202)',
 66,
 u'(40.678723, -73.9529869)',
 66,
 u'(40.7629663, -73.9739693)',
 65,
 u'(40.8380117, -73.8732802)',
 65,
 u'(40.7457274, -73.9781227)',
 65,
 u'(40.7515235, -73.9939473)',
 65,
 u'(40.7460347, -73.9344002)',
 65,
 u'(40.749824, -73.9722023)',
 65,
 u'(40.7585332, -73.9888427)',
 64,
 u'(40.8786453, -73.871598)',
 64,
 u'(40.7850321, -73.9405708)',
 63,
 u'(40.6666971, -73.7671284)',
 63,
 u'(40.6807, -73.8446429)',
 63,
 u'(40.7014547, -73.9896203)',
 63,
 u'(40.7373607, -73.996839)',
 63,
 u'(40.7611802, -73.9579029)',
 63,
 u'(40.7491025, -73.9920058)',
 63,
 u'(40.7184302, -74.0005303)',
 63,
 u'(40.758981, -73.9959428)',
 63,
 u'(40.7821423, -73.8248379)',
 62,
 u'(40.8617006, -73.8913807)',
 62,
 u'(40.7549013, -73.7454772)',
 62,
 u'(40.7197624, -73.9447576)',
 62,
 u'(40.8687708, -73.8317333)',
 62,
 u'(40.7185558, -73.9882)',
 62,
 u'(40.7170989, -73.9985895)',
 61,
 u'(40.696197, -73.9887629)',
 61,
 u'(40.8077723, -73.9454833)',
 61,
 u'(40.68424, -73.8460949)',
 61,
 u'(40.7044959, -73.817418)',
 61,
 u'(40.7597902, -73.9879256)',
 61,
 u'(40.8156907, -73.9582947)',
 60,
 u'(40.6685062, -73.9256052)',
 60,
 u'(40.750766, -73.9744433)',
 60,
 u'(40.764651, -73.823484)',
 60,
 u'(40.6784553, -73.9496774)',
 60,
 u'(40.7560353, -73.9869481)',
 60,
 u'(40.8410516, -73.944679)',
 59,
 u'(40.8953759, -73.8635575)',
 59,
 u'(40.7388307, -73.9831481)',
 59,
 u'(40.6899325, -73.9814728)',
 58,
 u'(40.7607762, -74.0021839)',
 58,
 u'(40.696131, -73.9871041)',
 58,
 u'(40.6844232, -73.978388)',
 58,
 u'(40.7447332, -73.9335895)',
 58,
 u'(40.7534818, -73.9808885)',
 58,
 u'(40.8636899, -73.9170643)',
 58,
 u'(40.7489156, -73.9373965)',
 58,
 u'(40.7624884, -73.9629739)',
 58,
 u'(40.7025952, -73.8552926)',
 58,
 u'(40.7605353, -73.9583509)',
 58,
 u'(40.7667145, -73.9828775)',
 57,
 u'(40.5704668, -74.1097619)',
 57,
 u'(40.7408961, -73.8996069)',
 57,
 u'(40.6671159, -73.8346499)',
 57,
 u'(40.7583388, -73.9964084)',
 57,
 u'(40.7375562, -73.8508811)',
 57,
 u'(40.759626, -73.9954735)',
 57,
 u'(40.7397514, -74.0025224)',
 56,
 u'(40.737833, -73.9356863)',
 56,
 u'(40.6817692, -73.9675328)',
 56,
 u'(40.7367906, -73.9784973)',
 56,
 u'(40.7598419, -73.9841751)',
 56,
 u'(40.6547385, -73.9069229)',
 56,
 u'(40.6694023, -73.9421971)',
 56,
 u'(40.7629537, -73.8319573)',
 56,
 u'(40.7570213, -74.004927)',
 56,
 u'(40.8071867, -73.9242798)',
 55,
 u'(40.784237, -73.9470697)',
 55,
 u'(40.7612344, -73.9638843)',
 55,
 u'(40.7313511, -73.9825546)',
 55,
 u'(40.8946624, -73.8613598)',
 55,
 u'(40.7656758, -73.9762353)',
 55,
 u'(40.6853239, -73.9807025)',
 55,
 u'(40.6915381, -73.99911)',
 55,
 u'(40.8782895, -73.8700582)',
 55,
 u'(40.6094167, -73.9676868)',
 54,
 u'(40.7476892, -74.0041684)',
 54,
 u'(40.7578281, -73.9930696)',
 54,
 u'(40.7401843, -73.986363)',
 54,
 u'(40.7225499, -74.006299)',
 54,
 u'(40.6848568, -73.9780417)',
 54,
 u'(40.7472966, -73.974044)',
 53,
 u'(40.6694768, -73.9199662)',
 53,
 u'(40.7616096, -73.9707499)',
 53,
 u'(40.6959932, -73.983213)',
 53,
 u'(40.7552921, -73.9949215)',
 53,
 u'(40.6320672, -73.9186024)',
 52,
 u'(40.7454414, -73.9753944)',
 52,
 u'(40.6889031, -73.9809286)',
 52,
 u'(40.7067007, -74.0160467)',
 52,
 u'(40.6420578, -74.02042)',
 52,
 u'(40.8627551, -73.9010787)',
 52,
 u'(40.738552, -73.9996824)',
 52,
 u'(40.8626793, -73.9090397)',
 52,
 u'(40.7688025, -73.9583602)',
 52,
 u'(40.6082248, -74.1293966)',
 52,
 u'(40.8133899, -73.9562587)',
 52,
 u'(40.7454217, -73.9909669)',
 51,
 u'(40.6259754, -73.9762346)',
 51,
 u'(40.7679171, -73.9857147)',
 51,
 u'(40.8334144, -73.8590554)',
 51,
 u'(40.7599831, -73.9648018)',
 51,
 u'(40.7514468, -74.0014293)',
 51,
 u'(40.7497328, -73.9360965)',
 51,
 u'(40.7624202, -73.8275149)',
 50,
 u'(40.6891376, -73.9907077)',
 50,
 u'(40.725432, -73.996771)',
 50,
 u'(40.7655201, -73.9800367)',
 50,
 u'(40.7332923, -73.9871799)',
 50,
 u'(40.7583082, -73.9629257)',
 50,
 u'(40.7378861, -73.9809038)',
 49,
 u'(40.6866823, -73.9793644)',
 49,
 u'(40.7360047, -73.9936167)',
 49,
 u'(40.6721508, -73.8431812)',
 49,
 u'(40.7521198, -73.9776766)',
 49,
 u'(40.7678891, -73.9815125)',
 49,
 u'(40.7604566, -73.983731)',
 49,
 u'(40.747009, -73.9771875)',
 49,
 u'(40.7192038, -73.9903644)',
 49,
 u'(40.6425396, -73.8765111)',
 49,
 u'(40.6936492, -73.9833217)',
 49,
 u'(40.8773934, -73.8664909)',
 48,
 u'(40.7565272, -73.994019)',
 48,
 u'(40.7488862, -73.9758407)',
 48,
 u'(40.8050573, -73.9390342)',
 48,
 u'(40.7614858, -73.9605992)',
 48,
 u'(40.7688772, -73.9489716)',
 48,
 u'(40.7579729, -73.9855364)',
 48,
 u'(40.8810763, -73.8784859)',
 48,
 u'(40.7589494, -73.9684806)',
 48,
 u'(40.8463591, -73.844621)',
 48,
 u'(40.6689504, -73.9338885)',
 47,
 u'(40.5972673, -73.9986569)',
 47,
 u'(40.6924673, -73.8108147)',
 47,
 u'(40.7229337, -73.9886394)',
 47,
 u'(40.7177239, -73.9857652)',
 47,
 u'(40.8204372, -73.9362273)',
 47,
 u'(40.7367523, -73.8776702)',
 47,
 u'(40.7540925, -73.9920774)',
 47,
 u'(40.7676137, -73.9499947)',
 47,
 u'(40.766359, -73.8875543)',
 47,
 u'(40.7559505, -73.9907272)',
 47,
 u'(40.6548824, -73.9618804)',
 47,
 u'(40.7571447, -73.9935606)',
 47,
 u'(40.6698646, -73.9505022)',
 47,
 u'(40.7627471, -73.8332862)',
 47,
 u'(40.7573389, -73.986013)',
 46,
 u'(40.6881494, -73.8488335)',
 46,
 u'(40.7517013, -73.9864003)',
 46,
 u'(40.6806649, -73.9026216)',
 46,
 u'(40.6670811, -73.810322)',
 46,
 u'(40.7031657, -73.8166124)',
 46,
 u'(40.6977532, -73.8139159)',
 46,
 u'(40.7654813, -73.9136994)',
 46,
 u'(40.6763431, -73.910927)',
 46,
 u'(40.7563194, -73.8336777)',
 46,
 u'(40.7609059, -73.9669961)',
 46,
 u'(40.7691169, -73.9885593)',
 46,
 u'(40.7428752, -73.9339378)',
 46,
 u'(40.6541334, -73.9123297)',
 46,
 u'(40.7118451, -73.8597598)',
 46,
 u'(40.688922, -73.9991472)',
 46,
 u'(40.7534749, -73.9925287)',
 46,
 u'(40.760405, -73.9874743)',
 46,
 u'(40.6803904, -73.949557)',
 46,
 u'(40.8101738, -73.9511673)',
 45,
 u'(40.7140668, -73.9516237)',
 45,
 u'(40.755392, -73.8282803)',
 45,
 u'(40.7557807, -74.0019852)',
 45,
 u'(40.5789366, -73.9852115)',
 45,
 u'(40.7422847, -74.0044171)',
 45,
 u'(40.6781564, -73.9441507)',
 45,
 u'(40.633111, -73.9721609)',
 45,
 u'(40.7109059, -74.014457)',
 45,
 u'(40.7599125, -73.9588098)',
 45,
 u'(40.7639417, -73.8281463)',
 45,
 u'(40.7608574, -73.9610689)',
 45,
 u'(40.6769384, -73.9218247)',
 45,
 u'(40.7170219, -73.830499)',
 45,
 u'(40.7214535, -73.8439779)',
 45,
 u'(40.7484375, -73.9845604)',
 45,
 u'(40.7005823, -73.8077418)',
 44,
 u'(40.7259197, -73.8953397)',
 44,
 u'(40.822904, -73.8700399)',
 44,
 u'(40.7091579, -73.8410666)',
 44,
 u'(40.7256734, -74.0057798)',
 44,
 u'(40.7521904, -73.9934636)',
 44,
 u'(40.7533873, -73.996304)',
 44,
 u'(40.7621739, -73.7567868)',
 44,
 u'(40.7579074, -73.9892976)',
 44,
 u'(40.7336872, -73.92395)',
 44,
 u'(40.6503881, -73.958708)',
 43,
 u'(40.6969863, -73.9352238)',
 43,
 u'(40.758306, -73.8556084)',
 43,
 u'(40.7213532, -74.0046358)',
 43,
 u'(40.7286048, -74.0053146)',
 43,
 u'(40.7629131, -73.9697999)',
 43,
 u'(40.6241708, -73.9704715)',
 43,
 u'(40.7254507, -73.8377671)',
 43,
 u'(40.6936625, -73.8521639)',
 43,
 u'(40.6641936, -73.8411164)',
 43,
 u'(40.7572855, -73.9781153)',
 43,
 u'(40.6977347, -73.8140794)',
 43,
 u'(40.6975581, -73.8527719)',
 43,
 u'(40.740095, -73.8998482)',
 43,
 u'(40.6664524, -73.757631)',
 43,
 u'(40.6692499, -73.9394287)',
 43,
 u'(40.815755, -73.8952779)',
 43,
 u'(40.86832, -73.8331589)',
 43,
 u'(40.6661202, -73.8222416)',
 42,
 u'(40.7623963, -73.9786009)',
 42,
 u'(40.6916827, -73.9993335)',
 42,
 u'(40.7497247, -73.9836217)',
 42,
 u'(40.7304453, -73.9136638)',
 42,
 u'(40.7329414, -73.9203819)',
 42,
 u'(40.7707422, -73.9945485)',
 42,
 u'(40.763547, -73.9693376)',
 42,
 u'(40.6664063, -73.8026224)',
 42,
 u'(40.6835142, -73.9759509)',
 42,
 u'(40.674396, -73.8965093)',
 42,
 u'(40.71728, -73.9954294)',
 41,
 u'(40.7412749, -73.9753418)',
 41,
 u'(40.7460392, -73.9905157)',
 41,
 u'(40.7547072, -73.9916334)',
 41,
 u'(40.7509597, -73.9827227)',
 41,
 u'(40.7636578, -73.9734636)',
 41,
 u'(40.6772073, -73.897226)',
 41,
 u'(40.763645, -73.9776872)',
 41,
 u'(40.6385239, -73.9731855)',
 41,
 u'(40.8185601, -73.9273161)',
 41,
 u'(40.6981895, -73.9618989)',
 41,
 u'(40.7077158, -73.802787)',
 41,
 u'(40.6811205, -73.9644216)',
 41,
 u'(40.6675224, -73.7806252)',
 41,
 u'(40.6783196, -73.9469195)',
 41,
 u'(40.6896895, -73.9923627)',
 41,
 u'(40.6663098, -73.7916994)',
 41,
 u'(40.5861184, -73.9360334)',
 41,
 u'(40.762288, -73.9723632)',
 41,
 u'(40.7396752, -73.9345761)',
 41,
 u'(40.6637286, -73.9538481)',
 41,
 u'(40.8064149, -73.9422623)',
 41,
 u'(40.7820225, -73.9717231)',
 41,
 u'(40.6098096, -73.9224976)',
 41,
 u'(40.7354542, -73.9170371)',
 41,
 u'(40.7319494, -73.8634231)',
 41,
 u'(40.6656299, -73.7392073)',
 41,
 u'(40.7008398, -73.9949394)',
 41,
 u'(40.8089731, -73.9483252)',
 41,
 u'(40.7516577, -73.9901323)',
 41,
 u'(40.8627501, -73.9049326)',
 41,
 u'(40.8859908, -73.827914)',
 40,
 u'(40.766166, -73.9542464)',
 40,
 u'(40.7616592, -73.9865607)',
 40,
 u'(40.8240665, -73.9087095)',
 40,
 u'(40.8777986, -73.8680486)',
 40,
 u'(40.7151185, -73.832233)',
 40,
 u'(40.8036997, -73.9358171)',
 40,
 u'(40.6527684, -73.8862898)',
 40,
 u'(40.76226, -73.7569828)',
 40,
 u'(40.6652573, -73.7395512)',
 40,
 u'(40.7440288, -73.9261524)',
 40,
 u'(40.7165417, -73.9969843)',
 40,
 u'(40.7365231, -73.9283288)',
 40,
 u'(40.7640562, -73.9647563)',
 40,
 u'(40.7452931, -73.9984879)',
 40,
 u'(40.8401945, -73.9430642)',
 40,
 u'(40.6914356, -73.8906231)',
 40,
 u'(40.7323478, -73.9849394)',
 40,
 u'(40.6518653, -73.8653425)',
 40,
 u'(40.7047985, -74.0166846)',
 40,
 u'(40.6756249, -73.8987786)',
 40,
 u'(40.7303695, -73.9138714)',
 40,
 u'(40.8040684, -73.9311544)',
 40,
 u'(40.7517478, -73.9708047)',
 40,
 u'(40.8934115, -73.8573621)',
 40,
 u'(40.6538055, -73.9306058)',
 40,
 u'(40.8653624, -73.8704197)',
 40,
 u'(40.7496708, -73.9952973)',
 40,
 u'(40.7522807, -73.9896919)',
 40,
 u'(40.7596199, -73.9619648)',
 40,
 u'(40.6777156, -73.935859)',
 40,
 u'(40.6686479, -73.9283482)',
 39,
 u'(40.752316, -73.9859454)',
 39,
 u'(40.7529363, -73.9854869)',
 39,
 u'(40.672888, -73.9992169)',
 39,
 u'(40.7524046, -73.9244179)',
 39,
 u'(40.842052, -73.8379084)',
 39,
 u'(40.6718921, -73.8958679)',
 39,
 u'(40.7343762, -73.8734167)',
 39,
 u'(40.6056732, -74.0309361)',
 39,
 u'(40.7415488, -73.9895745)',
 39,
 u'(40.7151196, -73.7735714)',
 39,
 u'(40.6656136, -73.7356712)',
 39,
 u'(40.7756404, -73.9605114)',
 39,
 u'(40.664083, -73.9481671)',
 39,
 u'(40.7210624, -73.9981962)',
 39,
 u'(40.8454299, -73.9139752)',
 39,
 u'(40.828303, -73.8829509)',
 39,
 u'(40.6317075, -73.946481)',
 39,
 u'(40.7589746, -73.9189996)',
 39,
 u'(40.6667077, -73.8718221)',
 39,
 u'(40.7553303, -73.9911785)',
 39,
 u'(40.7180184, -73.9999567)',
 39,
 u'(40.8130953, -73.8982589)',
 39,
 u'(40.7546882, -73.9953547)',
 39,
 u'(40.6700084, -73.9532706)',
 39,
 u'(40.7528008, -73.9792862)',
 38,
 u'(40.5965113, -73.9078755)',
 38,
 u'(40.7564521, -73.9703154)',
 38,
 u'(40.6948378, -73.9839237)',
 38,
 u'(40.7437832, -73.9735076)',
 38,
 u'(40.7713758, -73.8771311)',
 38,
 u'(40.7535158, -73.9887858)',
 38,
 u'(40.7579112, -73.977653)',
 38,
 u'(40.6965588, -73.9809032)',
 38,
 u'(40.6556338, -73.9598617)',
 38,
 u'(40.7535538, -73.9850428)',
 38,
 u'(40.6338025, -73.8896944)',
 38,
 u'(40.6053345, -73.7552743)',
 38,
 u'(40.7935573, -73.967016)',
 38,
 u'(40.7353396, -73.916885)',
 38,
 u'(40.7090458, -73.8414531)',
 38,
 u'(40.6214926, -74.0262133)',
 38,
 u'(40.762106, -73.9601368)',
 38,
 u'(40.7210636, -73.7594419)',
 38,
 u'(40.6164151, -74.1035089)',
 38,
 u'(40.7621793, -73.9661291)',
 38,
 u'(40.8097014, -73.9030288)',
 38,
 u'(40.7136919, -74.0137542)',
 38,
 u'(40.688616, -73.9891681)',
 38,
 u'(40.7586447, -73.9813418)',
 38,
 u'(40.6538564, -74.0081666)',
 38,
 u'(40.7620943, -73.7569053)',
 38,
 u'(40.7542505, -73.9689773)',
 38,
 u'(40.6265698, -73.9709207)',
 38,
 u'(40.7619942, -73.7584818)',
 38,
 u'(40.7446461, -73.7703999)',
 38,
 u'(40.6607702, -73.9197423)',
 38,
 u'(40.7304639, -73.9514819)',
 38,
 u'(40.7615472, -73.8311197)',
 38,
 u'(40.7529763, -73.9102326)',
 38,
 u'(40.6673505, -73.7699326)',
 38,
 u'(40.7591644, -73.9883913)',
 38,
 u'(40.8476674, -73.9010217)',
 37,
 u'(40.5779945, -73.9596347)',
 37,
 u'(40.6517331, -73.930381)',
 37,
 u'(40.8644625, -73.9189434)',
 37,
 u'(40.7418634, -73.9075049)',
 37,
 u'(40.7353901, -73.9751095)',
 37,
 u'(40.7713071, -73.8766313)',
 37,
 u'(40.6227987, -74.0283499)',
 37,
 u'(40.7152372, -74.0133794)',
 37,
 u'(40.6701245, -73.9552712)',
 37,
 u'(40.671645, -73.9625737)',
 37,
 u'(40.7872263, -73.9541633)',
 37,
 u'(40.7617706, -73.979056)',
 37,
 u'(40.7497883, -73.9877686)',
 37,
 u'(40.7528546, -73.9929799)',
 37,
 u'(40.7423751, -74.0087909)',
 37,
 u'(40.7497063, -73.9915618)',
 37,
 u'(40.766852, -73.9537478)',
 37,
 u'(40.727873, -73.9291223)',
 37,
 u'(40.6605938, -73.9313269)',
 37,
 u'(40.7416232, -73.9937353)',
 37,
 u'(40.6524639, -73.9228481)',
 37,
 u'(40.8812664, -73.8387425)',
 37,
 u'(40.7470784, -73.9813415)',
 37,
 u'(40.7546608, -73.8331043)',
 37,
 u'(40.6668946, -73.8054526)',
 37,
 u'(40.7591044, -73.9921418)',
 37,
 u'(40.758537, -73.9772016)',
 37,
 u'(40.7158555, -73.9949534)',
 37,
 u'(40.7626784, -73.9543321)',
 37,
 u'(40.8173878, -73.922758)',
 37,
 u'(40.8617318, -73.9118139)',
 36,
 u'(40.6783648, -73.7794791)',
 36,
 u'(40.7616682, -73.9749156)',
 36,
 u'(40.76132, -73.9170907)',
 36,
 u'(40.7402725, -73.8958512)',
 36,
 u'(40.6361331, -73.9727361)',
 36,
 u'(40.804696, -73.9223863)',
 36,
 u'(40.6543162, -73.9221576)',
 36,
 u'(40.6663969, -73.7385662)',
 36,
 u'(40.5958903, -74.0858762)',
 36,
 u'(40.7558686, -73.9982097)',
 36,
 u'(40.7007255, -73.9419319)',
 36,
 u'(40.7633655, -73.9592408)',
 36,
 u'(40.7204364, -74.0066956)',
 36,
 u'(40.5798042, -73.9718339)',
 36,
 u'(40.7952524, -73.9732091)',
 36,
 u'(40.6911938, -73.9977679)',
 36,
 u'(40.6125498, -73.962859)',
 36,
 u'(40.8466586, -73.8961762)',
 36,
 u'(40.7622265, -73.9681866)',
 36,
 u'(40.7484685, -73.9924606)',
 36,
 u'(40.7703138, -73.9914004)',
 36,
 u'(40.6099861, -73.9623778)',
 36,
 u'(40.7831836, -73.9436089)',
 36,
 u'(40.7653588, -73.7442823)',
 36,
 u'(40.6433056, -73.9740952)',
 36,
 u'(40.6328856, -73.9476978)',
 36,
 u'(40.6801176, -73.7532369)',
 36,
 u'(40.8216382, -73.9390768)',
 35,
 u'(40.7131354, -74.0040581)',
 35,
 u'(40.7406926, -73.8441704)',
 35,
 u'(40.7503184, -73.9911106)',
 35,
 u'(40.7026172, -73.960572)',
 35,
 u'(40.6511499, -73.8900044)',
 35,
 u'(40.8081625, -73.9265219)',
 35,
 u'(40.8676918, -73.9212136)',
 35,
 u'(40.7565681, -73.990276)',
 35,
 u'(40.6094024, -74.0901074)',
 35,
 u'(40.7577322, -73.9968524)',
 35,
 u'(40.665508, -73.9927692)',
 35,
 u'(40.768891, -73.9820935)',
 35,
 u'(40.6276429, -73.8902159)',
 35,
 u'(40.7733356, -73.9550538)',
 35,
 u'(40.7516035, -73.9338317)',
 35,
 u'(40.7605247, -73.9799732)',
 35,
 u'(40.8160806, -73.9176873)',
 35,
 u'(40.6529272, -73.9593299)',
 35,
 u'(40.7851932, -73.9493331)',
 35,
 u'(40.8443435, -73.9147428)',
 35,
 u'(40.7225802, -73.9404817)',
 35,
 u'(40.8622592, -73.8958844)',
 35,
 u'(40.747925, -73.973607)',
 35,
 u'(40.7485121, -73.9887144)',
 35,
 u'(40.6667525, -73.7799356)',
 35,
 u'(40.7491017, -73.9840766)',
 35,
 u'(40.751081, -73.9868516)',
 34,
 u'(40.7571844, -73.8339571)',
 34,
 u'(40.6792042, -73.9552939)',
 34,
 u'(40.6635186, -73.9572076)',
 34,
 u'(40.7365615, -73.9890159)',
 34,
 u'(40.7463915, -73.9776353)',
 34,
 u'(40.8177952, -73.8931829)',
 34,
 u'(40.838846, -73.8781619)',
 34,
 u'(40.7349628, -73.9797897)',
 34,
 u'(40.7892055, -73.9548156)',
 34,
 u'(40.7616074, -73.9903149)',
 34,
 ...]

In [16]:
df.select("CONTRIBUTING_FACTOR_VEHICLE_2").distinct().rdd.flatMap(lambda x: x).collect()

[u'Following Too Closely',
 u'Traffic Control Disregarded',
 u'Accelerator Defective',
 u'Windshield Inadequate',
 u'Unsafe Speed',
 u'Shoulders Defective/Improper',
 u'Oversized Vehicle',
 u'Lane Marking Improper/Inadequate',
 u'Passing or Lane Usage Improper',
 u'Other Lighting Defects',
 None,
 u'Aggressive Driving/Road Rage',
 u'Other Vehicular',
 u'Driver Inexperience',
 u'Tow Hitch Defective',
 u'Unspecified',
 u'Pavement Defective',
 u'Prescription Medication',
 u'Cell Phone (hand-held)',
 u'View Obstructed/Limited',
 u'Lost Consciousness',
 u'Reaction to Other Uninvolved Vehicle',
 u'Fell Asleep',
 u'Tire Failure/Inadequate',
 u'Outside Car Distraction',
 u'Drugs (Illegal)',
 u'Fatigued/Drowsy',
 u'Driver Inattention/Distraction',
 u'Failure to Keep Right',
 u'Obstruction/Debris',
 u'Unsafe Lane Changing',
 u'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion',
 u'Passenger Distraction',
 u'Alcohol Involvement',
 u'Illness',
 u'Traffic Control Device Improper/Non-Working',
 u'Backing Unsafely',
 u'Brakes Defective',
 u'Headlights Defective',
 u'Failure to Yield Right-of-Way',
 u'Animals Action',
 u'Turning Improperly',
 u'Glare',
 u'Steering Failure',
 u'Pavement Slippery',
 u'Physical Disability',
 u'Other Electronic Device',
 u'Cell Phone (hands-free)']

In [17]:
df.select("CONTRIBUTING_FACTOR_VEHICLE_1").distinct().rdd.flatMap(lambda x: x).collect()

[u'Following Too Closely',
 u'Traffic Control Disregarded',
 u'Accelerator Defective',
 u'Windshield Inadequate',
 u'Unsafe Speed',
 u'Shoulders Defective/Improper',
 u'Oversized Vehicle',
 u'Lane Marking Improper/Inadequate',
 u'Passing or Lane Usage Improper',
 u'Other Lighting Defects',
 None,
 u'Aggressive Driving/Road Rage',
 u'Other Vehicular',
 u'Driver Inexperience',
 u'Tow Hitch Defective',
 u'Unspecified',
 u'Pavement Defective',
 u'Prescription Medication',
 u'Cell Phone (hand-held)',
 u'View Obstructed/Limited',
 u'Lost Consciousness',
 u'Reaction to Other Uninvolved Vehicle',
 u'Fell Asleep',
 u'Tire Failure/Inadequate',
 u'Outside Car Distraction',
 u'Drugs (Illegal)',
 u'Fatigued/Drowsy',
 u'Driver Inattention/Distraction',
 u'Failure to Keep Right',
 u'Obstruction/Debris',
 u'Unsafe Lane Changing',
 u'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion',
 u'Passenger Distraction',
 u'Alcohol Involvement',
 u'Illness',
 u'Traffic Control Device Improper/Non-Working',
 u'Backing Unsafely',
 u'Brakes Defective',
 u'Headlights Defective',
 u'Failure to Yield Right-of-Way',
 u'Animals Action',
 u'Turning Improperly',
 u'Glare',
 u'Steering Failure',
 u'Pavement Slippery',
 u'Physical Disability',
 u'Other Electronic Device',
 u'Cell Phone (hands-free)']